spring:
  profiles:
    default: development
  application:
    name: user
  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 39000

---

spring:
  config:
    activate:
      on-profile: production
  main:
    banner-mode: log
  devtools:
    livereload:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/user-db?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: nownever
    password: nownever123!@#

---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/user-db?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: user-svc
    password: user-pass
