version: "3.8"

services:
  user-db:
    container_name: user-mariadb
    image: mariadb:10.6.4
    restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=user-db
      - MYSQL_ROOT_PASSWORD=nownever123!@#
      - MYSQL_USER=user-svc
      - MYSQL_PASSWORD=user-pass
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mariadb:/var/lib/mysql
