### API 등록
POST http://{{host-user}}/api/v1/api
Content-Type: application/json

{
  "name": "API",
  "description": "API 설명",
  "method": "GET"
}

> {%
client.test("API 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "API", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "API 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.method === "GET", "unexpected data.method: " + response.body.data.method);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
client.global.set("api_token", response.body.data.token)
%}

### API 조회
GET http://{{host-user}}/api/v1/api/{{api_token}}
Content-Type: application/json

> {%
client.test("API 조회", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "API", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "API 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.method === "GET", "unexpected data.method: " + response.body.data.method);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
%}

### API 기본 정보 변경
PUT http://{{host-user}}/api/v1/api/{{api_token}}
Content-Type: application/json

{
  "token": "{{api_token}}",
  "name": "API 변경",
  "description": "API 설명 변경",
  "method": "POST",
  "enable": false
}

> {%
client.test("API 기본 정보 변경", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "API 변경", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "API 설명 변경", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.method === "POST", "unexpected data.method: " + response.body.data.method);
    client.assert(response.body.data.enable === false, "unexpected data.enable: " + response.body.data.enable);
})
%}

### API 삭제
DELETE http://{{host-user}}/api/v1/api/{{api_token}}
Content-Type: application/json

> {%
client.test("API 삭제", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.token === String(client.global.get("api_token")), "unexpected data.token: " + response.body.data.token);
})
%}
