### 프로그램 등록
POST http://{{host-user}}/api/v1/program
Content-Type: application/json

{
  "name": "프로그램",
  "description": "프로그램 설명"
}

> {%
client.test("프로그램 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "프로그램", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "프로그램 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
client.global.set("program_token", response.body.data.token)
 %}

### 프로그램 조회
GET http://{{host-user}}/api/v1/program/{{program_token}}
Content-Type: application/json

> {%
client.test("프로그램 조회", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "프로그램", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "프로그램 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
 %}

### 프로그램 기본 정보 변경
PUT http://{{host-user}}/api/v1/program/{{program_token}}
Content-Type: application/json

{
  "token": "{{program_token}}",
  "name": "프로그램 변경",
  "description": "프로그램 변경 설명",
  "enable": false
}

> {%
client.test("프로그램 기본 정보 변경", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "프로그램 변경", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "프로그램 변경 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === false, "unexpected data.enable: " + response.body.data.enable);
})
 %}

### 프로그램 삭제
DELETE http://{{host-user}}/api/v1/program/{{program_token}}
Content-Type: application/json

> {%
client.test("프로그램 삭제", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.token === String(client.global.get("program_token")), "unexpected data.name: " + response.body.data.token);
})
 %}
