### 역할 등록
POST http://{{host-user}}/api/v1/role
Content-Type: application/json

{
  "name": "역할 1",
  "description": "역할 1 설명"
}

> {%
client.test("역할 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할 1", "unexpected data name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 1 설명", "unexpected data description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
client.global.set("role_token", response.body.data.token)
%}

### 역할 조회
GET http://{{host-user}}/api/v1/role/{{role_token}}
Content-Type: application/json

> {%
client.test("역할 조회", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할 1", "unexpected data name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 1 설명", "unexpected data description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
%}

### 역할 기본 정보 변경
PUT http://{{host-user}}/api/v1/role/{{role_token}}
Content-Type: application/json

{
  "token": "{{role_token}}",
  "name": "역할 기본 정보 변경",
  "description": "역할 기본 정보 변경 설명",
  "enable": false
}

> {%
client.test("역할 기본 정보 변경", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할 기본 정보 변경", "unexpected data name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 기본 정보 변경 설명", "unexpected data description: " + response.body.data.description);
    client.assert(response.body.data.enable === false, "unexpected data.enable: " + response.body.data.enable);
})
%}

### 역할 삭제
DELETE http://{{host-user}}/api/v1/role/{{role_token}}
Content-Type: application/json

> {%
client.test("역할 삭제", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.token === String(client.global.get("role_token")), "unexpected data name: " + response.body.data.name);
})
%}
