### 역할에 등록할 권한1 등록
POST http://{{host-user}}/api/v1/authority
Content-Type: application/json

{
  "name": "권한1",
  "description": "권한1 설명"
}

> {%
client.test("역할에 등록할 권한1 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "권한1", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "권한1 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
client.global.set("authority_token_1", response.body.data.token)
%}

### 역할에 등록할 권한2 등록
POST http://{{host-user}}/api/v1/authority
Content-Type: application/json

{
  "name": "권한2",
  "description": "권한2 설명"
}

> {%
client.test("역할에 등록할 권한2 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "권한2", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "권한2 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
client.global.set("authority_token_2", response.body.data.token)
%}

### 역할 등록
POST http://{{host-user}}/api/v1/role
Content-Type: application/json

{
  "name": "역할",
  "description": "역할 설명"
}

> {%
client.test("역할 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
})
client.global.set("role_token", response.body.data.token)
%}

### 역할에 권한1 등록
PUT http://{{host-user}}/api/v1/role/{{role_token}}/authority/{{authority_token_1}}
Content-Type: application/json

> {%
client.test("역할에 권한1 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.authorities[0].name === "권한1", "unexpected data.authorities[0].name: " + response.body.data.authorities[0].name);
    client.assert(response.body.data.authorities[0].description === "권한1 설명", "unexpected data.authorities[0].description: " + response.body.data.authorities[0].description);
    client.assert(response.body.data.authorities[0].enable === true, "unexpected data.authorities[0].enable: " + response.body.data.authorities[0].enable);
})
%}

### 역할에 권한2 등록
PUT http://{{host-user}}/api/v1/role/{{role_token}}/authority/{{authority_token_2}}
Content-Type: application/json

> {%
client.test("역할에 권한2 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.authorities[0].name === "권한1", "unexpected data.authorities[0].name: " + response.body.data.authorities[0].name);
    client.assert(response.body.data.authorities[0].description === "권한1 설명", "unexpected data.authorities[0].description: " + response.body.data.authorities[0].description);
    client.assert(response.body.data.authorities[0].enable === true, "unexpected data.authorities[0].enable: " + response.body.data.authorities[0].enable);
    client.assert(response.body.data.authorities[1].name === "권한2", "unexpected data.authorities[1].name: " + response.body.data.authorities[1].name);
    client.assert(response.body.data.authorities[1].description === "권한2 설명", "unexpected data.authorities[1].description: " + response.body.data.authorities[1].description);
    client.assert(response.body.data.authorities[1].enable === true, "unexpected data.authorities[1].enable: " + response.body.data.authorities[1].enable);
})
%}

### 역할 조회
GET http://{{host-user}}/api/v1/role/{{role_token}}
Content-Type: application/json

> {%
client.test("역할 조회", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할", "unexpected data name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 설명", "unexpected data description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.authorities[0].name === "권한1", "unexpected data.authorities[0].name: " + response.body.data.authorities[0].name);
    client.assert(response.body.data.authorities[0].description === "권한1 설명", "unexpected data.authorities[0].description: " + response.body.data.authorities[0].description);
    client.assert(response.body.data.authorities[0].enable === true, "unexpected data.authorities[0].enable: " + response.body.data.authorities[0].enable);
    client.assert(response.body.data.authorities[1].name === "권한2", "unexpected data.authorities[1].name: " + response.body.data.authorities[1].name);
    client.assert(response.body.data.authorities[1].description === "권한2 설명", "unexpected data.authorities[1].description: " + response.body.data.authorities[1].description);
    client.assert(response.body.data.authorities[1].enable === true, "unexpected data.authorities[1].enable: " + response.body.data.authorities[1].enable);
})
%}

### 역할에서 권한2 제거
DELETE http://{{host-user}}/api/v1/role/{{role_token}}/authority/{{authority_token_2}}
Content-Type: application/json

> {%
client.test("역할에서 권한2 제거", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "역할", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "역할 설명", "unexpected data.description: " + response.body.data.description);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.authorities[0].name === "권한1", "unexpected data.authorities[0].name: " + response.body.data.authorities[0].name);
    client.assert(response.body.data.authorities[0].description === "권한1 설명", "unexpected data.authorities[0].description: " + response.body.data.authorities[0].description);
    client.assert(response.body.data.authorities[0].enable === true, "unexpected data.authorities[0].enable: " + response.body.data.authorities[0].enable);
})
%}