### 화면 등록
POST http://{{host-user}}/api/v1/screen
Content-Type: application/json

{
  "name": "화면",
  "description": "화면 설명"
}

> {%
client.test("화면 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "화면", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "화면 설명", "unexpected data.description: " + response.body.data.description);
})
client.global.set("screen_token", response.body.data.token)
%}

### 화면 조회
GET http://{{host-user}}/api/v1/screen/{{screen_token}}
Content-Type: application/json

> {%
client.test("화면 조회", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "화면", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "화면 설명", "unexpected data.description: " + response.body.data.description);
})
%}

### 화면 기본 정보 변경
PUT http://{{host-user}}/api/v1/screen/{{screen_token}}
Content-Type: application/json

{
  "token": "{{screen_token}}",
  "name": "화면 변경",
  "description": "화면 설명 변경"
}

> {%
client.test("화면 기본 정보 변경", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "화면 변경", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.description === "화면 설명 변경", "unexpected data.description: " + response.body.data.description);
})
%}

### 화면 삭제
DELETE http://{{host-user}}/api/v1/screen/{{screen_token}}
Content-Type: application/json

> {%
client.test("화면 삭제", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.token === String(client.global.get("screen_token")), "unexpected data.token: " + response.body.data.token);
})
%}
