### 사용자 등록
POST http://{{host-user}}/api/v1/user
Content-Type: application/json

{
  "email": "email@gmail.com",
  "name": "사용자",
  "password": "비밀번호"
}

> {%
client.test("사용자 등록", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "사용자", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.password === "비밀번호", "unexpected data.password: " + response.body.data.password);
    client.assert(response.body.data.locked === false, "unexpected data.locked: " + response.body.data.locked);
    client.assert(response.body.data.email === "email@gmail.com", "unexpected data.email: " + response.body.data.email);
})
client.global.set("user_email", response.body.data.email)
%}

### 사용자 조회
GET http://{{host-user}}/api/v1/user/{{user_email}}
Content-Type: application/json

> {%
client.test("사용자 조회", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "사용자", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.password === "비밀번호", "unexpected data.password: " + response.body.data.password);
    client.assert(response.body.data.locked === false, "unexpected data.locked: " + response.body.data.locked);
    client.assert(response.body.data.email === "email@gmail.com", "unexpected data.email: " + response.body.data.email);
})
%}

### 사용자 비밀번호 변경
PUT http://{{host-user}}/api/v1/user/{{user_email}}/password
Content-Type: application/json

{
  "email": "{{user_email}}",
  "currentPassword": "비밀번호",
  "newPassword": "신규비밀번호"
}

> {%
client.test("사용자 비밀번호 변경", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.name === "사용자", "unexpected data.name: " + response.body.data.name);
    client.assert(response.body.data.enable === true, "unexpected data.enable: " + response.body.data.enable);
    client.assert(response.body.data.password === "신규비밀번호", "unexpected data.password: " + response.body.data.password);
    client.assert(response.body.data.locked === false, "unexpected data.locked: " + response.body.data.locked);
    client.assert(response.body.data.email === "email@gmail.com", "unexpected data.email: " + response.body.data.email);
})
%}

### 사용자 삭제
DELETE http://{{host-user}}/api/v1/user/{{user_email}}
Content-Type: application/json

> {%
client.test("사용자 삭제", function() {
    client.assert(response.status === 200, "unexpected http status: " + response.status);
    client.assert(response.body.data.email === String(client.global.get("user_email")), "unexpected data.email: " + response.body.data.email);
})
%}
